### ISSUE TITLE
'Name_submitted' column returned by the API doesn't returned the actual submitted name

### ISSUE THREAD

**Issue by Rekyt** [ojalaquellueva/TNRSapi#9]
Hey @ojalaquellueva 👋 (also tagging @bmaitner as I first uncovered the issue in the `TNRS` R package, but it doesn't seem to be the culprit here)
I was trying to match back my data based on originally submitted name to TNRS and realized there were some transformations made in the `Name_submitted` column by the TNRS API.

So let's say I want to match the following name: `Hypericum gentianoides (L.) Britton, Sterns & Poggenb.`
If I'm matching it with the TNRS API I'm getting back `Hypericum gentianoides (L.) Britton  Sterns & Poggenb.`
The comma between author names has been replaced by a space!

Is this done by technical limitations or is there preprocessing of submitted name?

I would argue that it would be nice for users to never transform the `Name_submitted` field to always be able to recover the initial names. (Also, the name is stripped of accents and special characters when applicable)

**Comment by ojalaquellueva** [comment]
@Rekyt (also @bmaitner): The TNRS applies some strict, old-school security rules that strip potentially malicious characters from the submitted name before importing it to the database for processing. These include the dreaded semi-colon, plus other punctuation and non-printing control characters potentially functional in MySQL, PHP or the shell. I wasn't aware that it stripped commas as well, but apparently it does. 

Because we cannot guarantee that the submitted name will be preserved exactly in all cases, we added the option of including a separate identifier for each name. If you include an integer identifier, it will be returned unaltered along with your resolved names; you can then use this identifier, not the submitted names, to join back to your original data. I always include identifiers with my names.

Stripping characters in this way is not how I'd approach the problem. However, I did not write the security code, so attempting to make changes would be time consuming and may have unintended consequences. As this is well-documented known behavior (mentioned in the TNRS publication), I will pass on making any changes.

**Comment by Rekyt** [comment]
Thanks for the very quick and clear answers! I definitely understand why and how does the TNRS API change some of the characters.
Then I will indeed use an ID to match my species names!

I'm closing this, but it would be nice to explain this on the TNRS website + the TNRS R package, so that users don't have bad surprises.
